services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_TURNSTILE_SITE_KEY: ${VITE_TURNSTILE_SITE_KEY}
        VITE_GOOGLE_TAG_MANAGER_ID: ${VITE_GOOGLE_TAG_MANAGER_ID}
        VITE_WHATSAPP_PHONE: ${VITE_WHATSAPP_PHONE}
        VITE_WHATSAPP_MESSAGE: ${VITE_WHATSAPP_MESSAGE}
    ports:
      - "80:80"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - path: ./.env
        required: false
    environment:
      NODE_ENV: production
      PRODUCTION: "true"
      TRUST_PROXY: "true"
